name: flutter_riverpod_overview
description: An overview of state management in Flutter using Riverpod.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # State management
  flutter_riverpod: 2.3.6
  # DI
  get_it: 7.6.0
  # Network
  dio: 5.1.2
  # Navigation
  go_router: 7.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 2.0.0
  # State management
  riverpod_lint: 1.3.2

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
